In [12]:
import pandas as pd
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [5]:
df = pd.read_csv('human_essays_v1.5.csv')
df.head()

,prompt,essays,introduction,source,band
0,‘Tourism is always a force for good which enab...,The role of tourism in the world today is wide...,The role of tourism in the world today is wide...,http://ielts-yasi.englishlab.net/Get%20IELTS%2...,9.0
1,‘We should introduce laws to make businesses a...,The issue of equality for men and women at wor...,The issue of equality for men and women at wor...,http://ielts-yasi.englishlab.net/Get%20IELTS%2...,9.0
2,"""Although abuse of the system are inevitable, ...",Social welfare is an essential element of an a...,Social welfare is an essential element of an a...,https://bayanebartar.org/file-dl/library/IELTS...,none
3,"""Fatherhood ought to be emphasised as much as ...",I believe that child-rearing should be the res...,I believe that child-rearing should be the res...,https://bayanebartar.org/file-dl/library/IELTS...,none
4,“Not every thing that is learned is contained ...,For some centuries humanity has used books to ...,For some centuries humanity has used books to ...,https://www.ieltsbuddy.com/task-2-sample-writi...,none

In [13]:
df1 = df[df["introduction"].isna() | (df["introduction"] == "")]
len(df1)

1220

In [20]:
for index, row in df1.iterrows():
  sentences = sentences = nltk.sent_tokenize(row["essays"])
  intro = sentences[:3]
  text = " ".join(intro)
  df1.at[index, "introduction"] = text

df1.to_csv("human_essays_v1.6_fill_blank.csv", index=False)

In [21]:
df2 = pd.read_csv("human_essays_v1.6_fill_blank.csv")
df2

,prompt,essays,introduction,source,band
0,A lot of people believe that the amount of vio...,The question of whether the amount of violence...,The question of whether the amount of violence...,https://bayanebartar.org/file-dl/library/IELTS...,none
1,A person’s worth nowadays seems to be judged a...,There are numerous ways in which a person can ...,There are numerous ways in which a person can ...,https://ted-ielts.com/task-achievement/,9
2,A person’s worth nowadays seems to be judged a...,Status and money are highly valued in today’s ...,Status and money are highly valued in today’s ...,https://www.ieltstutors.org/wp-content/uploads...,none
3,A person’s worth nowadays seems to be judged a...,It is pity to see a person’s worth nowadays to...,It is pity to see a person’s worth nowadays to...,https://www.ieltsbuddy.com/moral-values-essays...,none
4,A report written in the 1960s made the followi...,It is true that there have been great advances...,It is true that there have been great advances...,ebook,6+
...,...,...,...,...,...
1215,Young people are leaving their homes in rural ...,The comparison of standards of the cities and ...,The comparison of standards of the cities and ...,https://www.ieltsbuddy.com/ielts-band-7-essay-...,7
1216,Young people in the modern world seem to have ...,I would agree that young people today play a b...,I would agree that young people today play a b...,ebook,6+
1217,Young people who commit crimes should be treat...,There is an opinion that young offenders shoul...,There is an opinion that young offenders shoul...,https://quickwithus.com/wp-content/uploads/201...,none
1218,Young people who commit crimes should be treat...,Whether juvenile offenders should be treated i...,Whether juvenile offenders should be treated i...,write with travis,9
1219,Zoos are inhumane and should be abolished. To ...,Many people believe that there should be no zo...,Many people believe that there should be no zo...,Barron's Writing IELTS for the IELTS,Barron